name: CI/CD Pipeline

on:
  push:
    branches:
      - master
#1
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t myapp .  

    - name: Push Docker image to Docker Hub
      run: |
        docker tag myapp yourusername/myapp:latest
        docker push yourusername/myapp:latest

    - name: Run Docker container locally (opcional, para testar)
      run: |
        docker run -d -p 3000:3000 --name myapp yourusername/myapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to AWS EC2
      env:
        EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
      run: |
        echo "$EC2_PRIVATE_KEY" | tee private_key.pem > /dev/null
        chmod 600 private_key.pem

        ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@$EC2_PUBLIC_IP << 'EOF'
          sudo yum install -y docker
          sudo service docker start

          docker login -u yourusername -p ${{ secrets.DOCKER_TOKEN }}

          docker stop myapp || true
          docker rm myapp || true

          docker pull yourusername/myapp:latest
          docker run -d -p 3000:3000 --name myapp --restart unless-stopped yourusername/myapp:latest
        EOF
